export const booksListMock = {
    "key": "/subjects/finance",
    "name": "finance",
    "subject_type": "subject",
    "work_count": 82564,
    "works": [
      {
        "key": "/works/OL14903581W",
        "title": "Laws, etc",
        "edition_count": 3456,
        "cover_id": 11505604,
        "cover_edition_key": "OL10053776M",
        "subject": [
          "Law",
          "Statutes",
          "Law and legislation",
          "Great Britain",
          "World War, 1914-1918",
          "Gt. Brit",
          "Social security",
          "Delegated legislation",
          "Indexes",
          "Public health laws",
          "Finance",
          "Periodicals",
          "Domestic relations",
          "Patent laws and legislation",
          "Early works to 1800",
          "Cattle",
          "Law, Anglo-Saxon",
          "Local government",
          "Postal service",
          "Consumer protection",
          "Taxation",
          "Educational law and legislation",
          "Economic aspects of World War, 1914-1918",
          "Diseases",
          "Legislation",
          "Consumer credit",
          "Income tax",
          "Military law",
          "Commercial law",
          "Veterinary Quarantine",
          "Government securities",
          "Laws, statutes",
          "Old age pensions",
          "Militia",
          "Life insurance",
          "Weights and measures",
          "Prevention",
          "Trade regulation",
          "Rent",
          "Drill and minor tactics",
          "Food law and legislation",
          "Food conservation",
          "Great britain, politics and government, 1997-2010",
          "Law, great britain",
          "Social security, great britain",
          "Social security, law and legislation",
          "Economic aspects"
        ],
        "ia_collection": [
          "americana",
          "cdl",
          "inlibrary",
          "internetarchivebooks",
          "printdisabled"
        ],
        "lendinglibrary": false,
        "printdisabled": true,
        "lending_edition": "OL7025343M",
        "lending_identifier": "foodsupplymanual00grearich",
        "authors": [
          {
            "key": "/authors/OL46053A",
            "name": "Great Britain."
          },
          {
            "key": "/authors/OL4489781A",
            "name": "United States. General Accounting Office"
          }
        ],
        "first_publish_year": 1691,
        "ia": "foodsupplymanual00grearich",
        "public_scan": true,
        "has_fulltext": true,
        "availability": {
          "status": "open",
          "available_to_browse": false,
          "available_to_borrow": false,
          "available_to_waitlist": false,
          "is_printdisabled": false,
          "is_readable": true,
          "is_lendable": false,
          "is_previewable": true,
          "identifier": "foodsupplymanual00grearich",
          "isbn": null,
          "oclc": null,
          "openlibrary_work": "OL14903581W",
          "openlibrary_edition": "OL7025343M",
          "last_loan_date": null,
          "num_waitlist": null,
          "last_waitlist_date": null,
          "is_restricted": false,
          "is_browseable": false,
          "__src__": "core.models.lending.get_availability"
        }
      },
      {
        "key": "/works/OL565229W",
        "title": "Financial audit",
        "edition_count": 402,
        "cover_id": null,
        "cover_edition_key": null,
        "subject": [
          "American Battle Monuments Commission",
          "Auditing",
          "Roads",
          "Finance",
          "District of Columbia Highway Trust Fund",
          "Student loans",
          "Law and legislation",
          "Student aid",
          "United States",
          "United States. Department of Education",
          "Appropriations and expenditures",
          "Accounting",
          "Medicare",
          "Medicare Payment Advisory Commission (U.S.)",
          "Public Finance",
          "Consolidated Financial statements",
          "Executive impoundment of appropriated funds"
        ],
        "ia_collection": [
          ""
        ],
        "lendinglibrary": false,
        "printdisabled": false,
        "lending_edition": "",
        "lending_identifier": "",
        "authors": [],
        "first_publish_year": 1943,
        "ia": null,
        "public_scan": false,
        "has_fulltext": false
      },
      {
        "key": "/works/OL12548230W",
        "title": "Circulaire a MM. les curés du diocèse",
        "edition_count": 362,
        "cover_id": 8245240,
        "cover_edition_key": "OL19767123M",
        "subject": [
          "Fires",
          "Church and social problems",
          "Finance",
          "Catholic Church",
          "Incendies",
          "Finances",
          "Église catholique",
          "Église et problèmes sociaux"
        ],
        "ia_collection": [
          "additional_collections",
          "microfilm",
          "toronto",
          "university_of_alberta_libraries",
          "university_of_alberta_libraries_microfilm"
        ],
        "lendinglibrary": false,
        "printdisabled": false,
        "lending_edition": "OL19767123M",
        "lending_identifier": "cihm_56156",
        "authors": [
          {
            "key": "/authors/OL5561187A",
            "name": "Charles-François Baillargeon"
          }
        ],
        "first_publish_year": 1986,
        "ia": "cihm_56156",
        "public_scan": true,
        "has_fulltext": true,
        "availability": {
          "status": "open",
          "available_to_browse": false,
          "available_to_borrow": false,
          "available_to_waitlist": false,
          "is_printdisabled": false,
          "is_readable": true,
          "is_lendable": false,
          "is_previewable": true,
          "identifier": "cihm_56156",
          "isbn": "0665561563",
          "oclc": null,
          "openlibrary_work": "OL12548230W",
          "openlibrary_edition": "OL19767123M",
          "last_loan_date": null,
          "num_waitlist": null,
          "last_waitlist_date": null,
          "is_restricted": false,
          "is_browseable": false,
          "__src__": "core.models.lending.get_availability"
        }
      },
      {
        "key": "/works/OL1513584W",
        "title": "By the King",
        "edition_count": 169,
        "cover_id": null,
        "cover_edition_key": null,
        "subject": [
          "Administration",
          "Administration of Criminal justice",
          "Alum industry",
          "Anti-Catholicism",
          "Apprentices",
          "Armor",
          "Bartholomew Fair (1625 : Smithfield, London, England)",
          "Bartholomew Fair (1637 : Smithfield, London, England)",
          "Bermuda Islands",
          "Billeting",
          "Bird trapping",
          "Bits (Bridles)",
          "Bow and arrow",
          "Buckle industry",
          "Building laws",
          "Butter trade",
          "Catholics",
          "Censorship",
          "Charitable contributions",
          "Church of England",
          "Civil status",
          "Coinage",
          "Colonies",
          "Commerce",
          "Company of Merchant Adventurers of England",
          "Copyhold",
          "Corporation of Gardeners",
          "Corporation of Sope-makers of London",
          "Court and courtiers",
          "Courts",
          "Courts and courtiers",
          "Criminal justice, Administration of",
          "Dairy products industry",
          "Deer hunting",
          "Defenses",
          "Dissenters, Religious",
          "Dyes and dyeing",
          "Early works to 1800",
          "East India Company",
          "Employment",
          "England",
          "England and Wales",
          "England and Wales. Army",
          "England and Wales. Exchequer",
          "England and Wales. Parliament",
          "England and Wales. Parliament. House of Commons",
          "England and Wales. Royal Navy",
          "English mercenaries",
          "Equipment",
          "Equipment and supplies",
          "Europe",
          "Exports",
          "Fairs",
          "Fasts and feasts",
          "Finance",
          "Finance, Public",
          "Fishery policy",
          "Fleetstreet Riot, London, England, 10 July 1629",
          "Food",
          "Food law and legislation",
          "Food prices",
          "Food supply",
          "Foreign relations",
          "Foreign trade regulation",
          "Forfeiture",
          "Fowling",
          "Freedom of movement",
          "Goldweights",
          "Grain trade",
          "Great Britain",
          "Great Britain Civil War, 1642-1649",
          "Guild of Weavers of London",
          "Guilds",
          "Gunpowder",
          "Gunpowder industry",
          "Hat trade",
          "Hides and skins industry",
          "Hides and skins trade",
          "History",
          "History, Military",
          "History, Naval",
          "Horsemanship",
          "Huguenots",
          "Indians of North America",
          "Introduction à la vie dévote",
          "Knights and knighthood",
          "Land tenure",
          "Law and legislation",
          "Legal status, laws",
          "Legal tender",
          "Lent",
          "Liturgy",
          "Madder",
          "Maintenance and repair",
          "Meat industry and trade",
          "Metal-workers",
          "Military History",
          "Military discipline",
          "Military readiness",
          "Military supplies",
          "Monetary policy",
          "Monopolies",
          "Mutiny",
          "Naval History",
          "Naval deserters",
          "Nitrogen industries",
          "Officials and employees",
          "Our Lady Fair (1637 : Southwark, London, England)",
          "Passports",
          "Persecution",
          "Pewter",
          "Plague",
          "Politics and government",
          "Poor laws",
          "Postal service",
          "Prevention",
          "Prices",
          "Printing industry",
          "Privateering",
          "Prize law",
          "Procedure (Law)",
          "Proclamations",
          "Public Finance",
          "Quality",
          "Quality control",
          "Reformed Church",
          "Relations",
          "Religious Dissenters",
          "Religious refugees",
          "Riots",
          "Roads",
          "Rogues and vagabonds",
          "Royal forests",
          "Royal households",
          "Royal touch",
          "Saltpeter industry",
          "Scrofula",
          "Silk",
          "Silk industry",
          "Smuggling",
          "Society of Starch Makers of London",
          "Soldiers",
          "Soldiers of fortune",
          "Sources",
          "Starch industry",
          "Stourbridge Fair (1625 : Barnwell, Northamptonshire)",
          "Taxation",
          "Tenement houses",
          "Terms of court",
          "Textile industry",
          "Tin industry",
          "Tobacco industry",
          "Tobacco use",
          "Trade associations",
          "Vagrancy",
          "Veterans",
          "Weapons",
          "Weights and measures",
          "Wellington Mutiny, 1640",
          "Wine and wine making",
          "Wire industry",
          "Wool industry",
          "Worshipful Company of Armourers and Brasiers in the City of London"
        ],
        "ia_collection": [
          ""
        ],
        "lendinglibrary": false,
        "printdisabled": false,
        "lending_edition": "",
        "lending_identifier": "",
        "authors": [
          {
            "key": "/authors/OL5097810A",
            "name": "England and Wales. Sovereign (1625-1649 : Charles I)."
          }
        ],
        "first_publish_year": 1625,
        "ia": null,
        "public_scan": false,
        "has_fulltext": false
      },
      {
        "key": "/works/OL565231W",
        "title": "Tax administration",
        "edition_count": 151,
        "cover_id": null,
        "cover_edition_key": null,
        "subject": [
          "Abstracts",
          "Abuse of rights",
          "Accounting",
          "Administrative agencies",
          "Alcohol",
          "Aliens",
          "Appropriations and expenditures",
          "Attitudes",
          "Auditing",
          "Automation",
          "Automobiles",
          "Bonds",
          "Boycotts",
          "Business enterprises",
          "Compliance auditing",
          "Corporations",
          "Correality and solidarity",
          "Corrupt practices",
          "Cost effectiveness",
          "Criminal investigation",
          "Customer services",
          "Data processing",
          "Earned income tax credit",
          "Electronic data interchange",
          "Employee attitude surveys",
          "Employees",
          "Enterprise zones",
          "Evaluation",
          "Excise tax",
          "Farm income",
          "Farmers",
          "Finance",
          "Flat-rate income tax",
          "Foreign Corporations",
          "Foreign Investments",
          "Foreign income",
          "Forms",
          "Fraud",
          "Fraud investigation",
          "Government policy",
          "Government publications",
          "Grants-in-aid",
          "Husband and wife",
          "Illegal aliens",
          "Income tax",
          "Information services",
          "Intergovernmental tax relations",
          "Internal revenue law",
          "International business enterprises",
          "Interpretation and construction",
          "Joint returns",
          "Law and legislation",
          "Management",
          "Married people",
          "Money laundering investigation",
          "Nonprofit organizations",
          "Officials and employees",
          "Older people",
          "Original issue discount (Bonds)",
          "Payroll tax",
          "Personnel management",
          "Poor",
          "Preferred stocks",
          "Prevention",
          "Public contracts",
          "Records and correspondence",
          "Reorganization",
          "Research",
          "Rules and practice",
          "Sales tax",
          "Self-employed",
          "Service industries workers",
          "Services for",
          "Single people",
          "Small business",
          "Sole proprietorship",
          "Spendings tax",
          "States",
          "Statistics",
          "Tax administration",
          "Tax administration and procedure",
          "Tax administration and procedures",
          "Tax auditing",
          "Tax collection",
          "Tax consultants",
          "Tax credits",
          "Tax deductions",
          "Tax evasion",
          "Tax exemption",
          "Tax incentives",
          "Tax penalties",
          "Tax protests and appeals",
          "Tax refunds",
          "Tax remission",
          "Tax returns",
          "Tax shelters",
          "Taxation",
          "Taxpayer Assistance Program",
          "Taxpayer compliance",
          "Technological innovations",
          "Telephone in business",
          "Telephone systems",
          "Training of",
          "Undercover operations",
          "United States",
          "United States. Internal Revenue Service",
          "United States. Internal Revenue Service. Criminal Investigation Division",
          "United States. Internal Revenue Service. Small Business/Self-Employed Division. Taxpayer Education & Communication",
          "United States. Internal Revenue Services",
          "United States. Office of Management and Budget",
          "Value-added tax",
          "Wages",
          "Waste in government spending",
          "Withholding tax"
        ],
        "ia_collection": [
          ""
        ],
        "lendinglibrary": false,
        "printdisabled": false,
        "lending_edition": "",
        "lending_identifier": "",
        "authors": [
          {
            "key": "/authors/OL4489781A",
            "name": "United States. General Accounting Office"
          }
        ],
        "first_publish_year": 1986,
        "ia": null,
        "public_scan": false,
        "has_fulltext": false
      },
      {
        "key": "/works/OL891636W",
        "title": "The art of money getting, or, Golden rules for money getting",
        "edition_count": 145,
        "cover_id": 756095,
        "cover_edition_key": "OL8408265M",
        "subject": [
          "Success",
          "Finance",
          "Nonfiction",
          "Self-Improvement",
          "Success in business",
          "Finance, personal",
          "Income",
          "Commerce",
          "Business",
          "Self-help techniques"
        ],
        "ia_collection": [
          "inlibrary",
          "internetarchivebooks",
          "printdisabled"
        ],
        "lendinglibrary": false,
        "printdisabled": true,
        "lending_edition": "OL35672004M",
        "lending_identifier": "artofmoneygettin0000ptba",
        "authors": [
          {
            "key": "/authors/OL78901A",
            "name": "P. T. Barnum"
          }
        ],
        "first_publish_year": 1880,
        "ia": "artofmoneygettin0000ptba",
        "public_scan": true,
        "has_fulltext": true,
        "availability": {
          "status": "borrow_available",
          "available_to_browse": true,
          "available_to_borrow": false,
          "available_to_waitlist": false,
          "is_printdisabled": true,
          "is_readable": false,
          "is_lendable": true,
          "is_previewable": true,
          "identifier": "artofmoneygettin0000ptba",
          "isbn": "9781603863346",
          "oclc": null,
          "openlibrary_work": "OL891636W",
          "openlibrary_edition": "OL35672004M",
          "last_loan_date": null,
          "num_waitlist": null,
          "last_waitlist_date": null,
          "is_restricted": true,
          "is_browseable": true,
          "__src__": "core.models.lending.get_availability"
        }
      },
      {
        "key": "/works/OL565230W",
        "title": "U.S. Postal Service",
        "edition_count": 134,
        "cover_id": null,
        "cover_edition_key": null,
        "subject": [
          "Accounting",
          "Address correction service",
          "Aguirre International",
          "Anthrax",
          "Appropriations and expenditures",
          "Auditing",
          "Automation",
          "Biological decontamination",
          "Bioterrorism",
          "Competition",
          "Consumer satisfaction",
          "Corporate governance",
          "Costs",
          "Criminal investigation",
          "Customer services",
          "Disclosure of information",
          "Diversity in the workplace",
          "Electronic commerce",
          "Employee screening",
          "Employee-management relations in government",
          "Employees",
          "Employment",
          "Evaluation",
          "Express service",
          "Finance",
          "Foreign mail",
          "Fraud",
          "Government policy",
          "Government purchasing of real property",
          "Industrial relations",
          "International Competition",
          "International cooperation",
          "Land use",
          "Law and legislation",
          "Letter mail handling",
          "Mail surveys",
          "Management",
          "Minorities",
          "Officials and employees",
          "Parcel post",
          "Personnel management",
          "Planning",
          "Post office stations and branches",
          "Postal rates",
          "Postal service",
          "Postmasters",
          "Prevention",
          "Privacy",
          "Privatization",
          "Procurement",
          "Promotions",
          "Rates",
          "Reform",
          "Reorganization",
          "Research",
          "Right of Privacy",
          "Rules and practice",
          "Salaries",
          "Statistics",
          "Telecommunication policy",
          "Third-class matter",
          "United States",
          "United States Postal Service",
          "United States Postal Service. Postal Inspection Service",
          "United States Postal Servicen",
          "United States Postal Services",
          "United States. Postal Service",
          "Women",
          "Work sharing",
          "United States. Postal service"
        ],
        "ia_collection": [
          ""
        ],
        "lendinglibrary": false,
        "printdisabled": false,
        "lending_edition": "",
        "lending_identifier": "",
        "authors": [
          {
            "key": "/authors/OL4489781A",
            "name": "United States. General Accounting Office"
          }
        ],
        "first_publish_year": 1987,
        "ia": null,
        "public_scan": false,
        "has_fulltext": false
      },
      {
        "key": "/works/OL2829091W",
        "title": "Reconfigurable Processor Array A Bit Sliced Parallel Computer (USA)",
        "edition_count": 132,
        "cover_id": 8237007,
        "cover_edition_key": "OL10230058M",
        "subject": [
          "Industrial safety",
          "Management",
          "Macroeconomics",
          "Microeconomics",
          "Economics",
          "Database management",
          "DBase III plus (Computer file)",
          "Marketing",
          "Case studies",
          "Cases",
          "Collective labor agreements",
          "IBM Personal Computer",
          "Lotus 1-2-3 (Computer file)",
          "Programming",
          "PC-DOS (Computer file)",
          "WordPerfect (Computer file)",
          "Problems, exercises",
          "Business mathematics",
          "Economic conditions",
          "Managerial accounting",
          "Examinations, questions",
          "Corporations",
          "Finance",
          "Heat",
          "Transmission",
          "DBASE III plus (Computer file)",
          "Capital market",
          "Study and teaching",
          "Financial analysis"
        ],
        "ia_collection": [
          "inlibrary",
          "internetarchivebooks",
          "printdisabled",
          "wrlc-ol"
        ],
        "lendinglibrary": false,
        "printdisabled": true,
        "lending_edition": "OL10230291M",
        "lending_identifier": "reconfigurablepr0000arus_o6v1",
        "authors": [
          {
            "key": "/authors/OL422557A",
            "name": "A. Rushton"
          }
        ],
        "first_publish_year": 1986,
        "ia": "reconfigurablepr0000arus_o6v1",
        "public_scan": false,
        "has_fulltext": true,
        "availability": {
          "status": "borrow_available",
          "available_to_browse": true,
          "available_to_borrow": false,
          "available_to_waitlist": false,
          "is_printdisabled": true,
          "is_readable": false,
          "is_lendable": true,
          "is_previewable": true,
          "identifier": "reconfigurablepr0000arus_o6v1",
          "isbn": "9780256084948",
          "oclc": null,
          "openlibrary_work": "OL2829091W",
          "openlibrary_edition": "OL10230291M",
          "last_loan_date": null,
          "num_waitlist": null,
          "last_waitlist_date": null,
          "is_restricted": true,
          "is_browseable": true,
          "__src__": "core.models.lending.get_availability"
        }
      },
      {
        "key": "/works/OL11350239W",
        "title": "Laws, etc",
        "edition_count": 124,
        "cover_id": 11761863,
        "cover_edition_key": "OL15402753M",
        "subject": [
          "Armies",
          "Attachment and garnishment",
          "Church of England",
          "Customs administration",
          "Early works to 1800",
          "England and Wales",
          "England and Wales. Army",
          "England and Wales. Parliament",
          "Equipment",
          "Finance",
          "Foreign trade regulation",
          "Government",
          "Great Britain Civil War, 1642-1649",
          "History",
          "History, Military",
          "Internal revenue law",
          "Law",
          "Law and legislation",
          "Liquor industry",
          "Liturgy",
          "Meat",
          "Military History",
          "Mines and mineral resources",
          "Ordination",
          "Pensions",
          "Plague",
          "Politics and government",
          "Postal service",
          "Protestants",
          "Public welfare",
          "Recruiting, enlistment",
          "Salaries",
          "Salt",
          "Seal",
          "Session laws",
          "Solemn League and Covenant",
          "Sources",
          "Tariff",
          "Tax collection",
          "Taxation",
          "Taxation of articles of consumption",
          "Westminster Assembly (1643-1652)",
          "Wine and wine making",
          "Controversial literature",
          "Statues",
          "Law reports, digests",
          "Jesuits"
        ],
        "ia_collection": [
          "Boston_College_Library",
          "americana",
          "blc"
        ],
        "lendinglibrary": false,
        "printdisabled": false,
        "lending_edition": "OL15402753M",
        "lending_identifier": "annoxxviireginel00engl",
        "authors": [
          {
            "key": "/authors/OL4768277A",
            "name": "England and Wales"
          }
        ],
        "first_publish_year": 1513,
        "ia": "annoxxviireginel00engl",
        "public_scan": true,
        "has_fulltext": true,
        "availability": {
          "status": "open",
          "available_to_browse": false,
          "available_to_borrow": false,
          "available_to_waitlist": false,
          "is_printdisabled": false,
          "is_readable": true,
          "is_lendable": false,
          "is_previewable": true,
          "identifier": "annoxxviireginel00engl",
          "isbn": null,
          "oclc": null,
          "openlibrary_work": "OL11350239W",
          "openlibrary_edition": "OL15402753M",
          "last_loan_date": null,
          "num_waitlist": null,
          "last_waitlist_date": null,
          "is_restricted": false,
          "is_browseable": false,
          "__src__": "core.models.lending.get_availability"
        }
      },
      {
        "key": "/works/OL76827W",
        "title": "The Wealth of Nations",
        "edition_count": 123,
        "cover_id": 12816911,
        "cover_edition_key": "OL38580611M",
        "subject": [
          "Economische filosofie",
          "Communism",
          "Finance",
          "Business",
          "Open Library Staff Picks",
          "Economics",
          "Wealth",
          "Colonization",
          "Économie politique",
          "Early works to 1800",
          "Classical school of economics",
          "Nonfiction",
          "Colonies",
          "History",
          "Economics, philosophy",
          "Politics and government",
          "Social conditions",
          "Democracy",
          "BUSINESS & ECONOMICS",
          "General",
          "Reference",
          "United states, politics and government",
          "United states, social conditions",
          "Communism, germany",
          "Literature",
          "Collections"
        ],
        "ia_collection": [
          "Princeton",
          "americana",
          "binghamton-ol",
          "bostonpubliclibrary",
          "cdl",
          "cornell",
          "europeanlibraries",
          "framingham-ol",
          "inlibrary",
          "internetarchivebooks",
          "johnshopkins-ol",
          "lincolncollection",
          "oiseut",
          "openlibrary-d-ol",
          "printdisabled",
          "robarts",
          "toronto",
          "trinitycollege"
        ],
        "lendinglibrary": false,
        "printdisabled": true,
        "lending_edition": "OL7139753M",
        "lending_identifier": "inquiryintonatur01smituoft",
        "authors": [
          {
            "key": "/authors/OL39302A",
            "name": "Adam Smith"
          }
        ],
        "first_publish_year": 1776,
        "ia": "inquiryintonatur01smituoft",
        "public_scan": true,
        "has_fulltext": true,
        "availability": {
          "status": "open",
          "available_to_browse": false,
          "available_to_borrow": false,
          "available_to_waitlist": false,
          "is_printdisabled": false,
          "is_readable": true,
          "is_lendable": false,
          "is_previewable": true,
          "identifier": "inquiryintonatur01smituoft",
          "isbn": null,
          "oclc": null,
          "openlibrary_work": "OL76827W",
          "openlibrary_edition": "OL7139753M",
          "last_loan_date": null,
          "num_waitlist": null,
          "last_waitlist_date": null,
          "is_restricted": false,
          "is_browseable": false,
          "__src__": "core.models.lending.get_availability"
        }
      },
      {
        "key": "/works/OL10733909W",
        "title": "Financial audit",
        "edition_count": 116,
        "cover_id": null,
        "cover_edition_key": null,
        "subject": [
          "Accounting",
          "American Military assistance",
          "Appropriations and expenditures",
          "Appropriations and expenditures, 1994",
          "Appropriations and expenditures, 1995",
          "Appropriations and expenditures, 1996",
          "Armed Forces",
          "Auditing",
          "Budget",
          "Caucuses",
          "Child support",
          "Corporations, Government",
          "Corrupt practices",
          "Debts, Public",
          "Deregulation",
          "Electric industries",
          "Employees",
          "Evaluation",
          "Executive impoundment of appropriated funds",
          "Federal Deposit Insurance Corporation",
          "Finance",
          "Financial statements",
          "Flight training",
          "Food stamps",
          "Free trade",
          "Government Corporations",
          "Government lending",
          "Health promotion",
          "Housing development",
          "Information technology",
          "Insurance, Liability",
          "Insurance, Pension trust guaranty",
          "Interest rates",
          "Investment guaranty Insurance",
          "Law and legislation",
          "Liability Insurance",
          "Liability for oil pollution damages",
          "Management",
          "Medical care",
          "Military Flight navigators",
          "Military pensions",
          "National Economic Commission (U.S.)",
          "Officials and employees",
          "Pension Benefit Guaranty Corporation",
          "Pension trust guaranty Insurance",
          "Public Debts",
          "Resolution Trust Corporation (U.S.)",
          "Restaurant management",
          "Retirement",
          "Revenue sharing",
          "Rural Telephone Bank",
          "Salaries",
          "Savings and Loan Bailout, 1989-1995",
          "Savings and loan associations",
          "Supply and demand",
          "Timber",
          "Training of",
          "Trans-Alaska Pipeline Liability Fund (U.S.)",
          "United States",
          "United States Commission on Improving the Effectiveness of the United Nations",
          "United States. Agency for International Development",
          "United States. Air Force",
          "United States. Army",
          "United States. Army Aviation Systems Command",
          "United States. Army Tank-Automotive Command",
          "United States. Army Troop Support Command",
          "United States. Army. Corps of Engineers",
          "United States. Army. Missile Command",
          "United States. Bureau of the Public Debt",
          "United States. Congress",
          "United States. Congress. Office of the Attending Physician",
          "United States. Congress. Senate. Health Promotion Revolving Fund",
          "United States. Dept. of Agriculture",
          "United States. Dept. of Defense",
          "United States. Dept. of Energy",
          "United States. Dept. of Veterans Affairs",
          "United States. Dept. of the Treasury",
          "United States. Federal Energy Regulatory Commission",
          "United States. Federal Housing Administration",
          "United States. General Services Administration",
          "United States. National Aeronautics and Space Administration",
          "United States. Navy",
          "United States. Office of Thrift Supervision",
          "United States. Panama Canal Commission",
          "Uranium enrichment",
          "V-22 Osprey (Transport plane)"
        ],
        "ia_collection": [
          ""
        ],
        "lendinglibrary": false,
        "printdisabled": false,
        "lending_edition": "",
        "lending_identifier": "",
        "authors": [
          {
            "key": "/authors/OL4489781A",
            "name": "United States. General Accounting Office"
          }
        ],
        "first_publish_year": 1975,
        "ia": null,
        "public_scan": false,
        "has_fulltext": false
      },
      {
        "key": "/works/OL565228W",
        "title": "Nuclear waste",
        "edition_count": 100,
        "cover_id": null,
        "cover_edition_key": null,
        "subject": [
          "Accidents",
          "Appropriations and expenditures",
          "Auditing",
          "Boring",
          "Cleanup",
          "Cleanup of radioactive waste sites",
          "Contracting out",
          "Cost control",
          "Cost of operation",
          "Costs",
          "Design and construction",
          "Economic aspects",
          "Environmental aspects",
          "Environmental aspects of Hazardous waste sites",
          "Environmental aspects of Nuclear power plants",
          "Environmental aspects of Nuclear reactors",
          "Environmental aspects of Nuclear weapons plants",
          "Environmental aspects of Radioactive waste disposal",
          "Environmental aspects of Radioactive waste sites",
          "Environmental aspects of United States",
          "Environmental aspects of United States.",
          "Environmental monitoring",
          "Estimates",
          "Evaluation",
          "Experiments",
          "Finance",
          "Government policy",
          "Groundwater",
          "Hanford Site (Wash.)",
          "Hazardous waste site remediation",
          "Hazardous waste sites",
          "Hazardous waste treatment facilities",
          "Hazardous wastes",
          "Idaho National Engineering and Environmental Laboratory",
          "Information services",
          "Iodine",
          "Isotopes",
          "Law and legislation",
          "Lawrence Livermore National Laboratory",
          "Lockheed Martin Advanced Environmental Systems (Firm)",
          "Management",
          "Measurement",
          "Mixed radioactive wastes",
          "Monitoring",
          "Nevada Nuclear Waste Storage Investigation Project (U.S.)",
          "Nuclear facilities",
          "Nuclear industry",
          "Nuclear power plants",
          "Nuclear reactors",
          "Nuclear weapons plants",
          "Planning",
          "Political aspects of Radioactive waste sites",
          "Pollution",
          "Procurement",
          "Public contracts",
          "Public relations",
          "Radioactive substances",
          "Radioactive waste disposal",
          "Radioactive waste disposal in the ground",
          "Radioactive waste sites",
          "Radioactive wastes",
          "Reactor fuel reprocessing",
          "Research",
          "Risk assessment",
          "Rules and practice",
          "Safety measures",
          "Safety regulations",
          "Savannah River Plant (E.I. du Pont de Nemours & Company)",
          "Savannah River Site (Westinghouse Savannah River Company)",
          "Spent reactor fuels",
          "Storage",
          "Storage tanks",
          "Technological innovations",
          "Transportation",
          "Transuranium elements",
          "United States",
          "United States Dept. of Energy",
          "United States Dept. of Energy. Hanford Site (Richland, Wash.)",
          "United States. Army. Corps of Engineers",
          "United States. Dept. of Energy",
          "United States. Dept. of Energy. Hanford Site",
          "United States. Dept. of Energy. Hanford Site (Richland, Wash.)",
          "United States. Dept. of Energy. Office of Environmental Management",
          "United States. Dept. of Energy. Office of Science and Technology",
          "United States. Office of the Nuclear Waste Negotiator",
          "Waste Isolation Pilot Plant (N.M.)",
          "Waste disposal",
          "Wells",
          "Westinghouse Hanford Company",
          "Zone of aeration",
          "United States. Department of Energy",
          "Radioactive waste repositories",
          "United States. Department of Energy. Office of Environmental Management",
          "United States. Department of Energy. Office of Science and Technology"
        ],
        "ia_collection": [
          ""
        ],
        "lendinglibrary": false,
        "printdisabled": false,
        "lending_edition": "",
        "lending_identifier": "",
        "authors": [
          {
            "key": "/authors/OL4489781A",
            "name": "United States. General Accounting Office"
          }
        ],
        "first_publish_year": 1900,
        "ia": null,
        "public_scan": false,
        "has_fulltext": false
      }
    ]
  }

export const bookMock = {
  "dewey_number": [
      "261.8"
  ],
  "last_modified": {
      "type": "/type/datetime",
      "value": "2019-10-31T21:05:54.651566"
  },
  "title": "Circulaire a MM. les cur\u00e9s du dioc\u00e8se",
  "created": {
      "type": "/type/datetime",
      "value": "2009-12-11T07:11:14.117483"
  },
  "covers": [
      8245240,
      7109395
  ],
  "subject_places": [
      "Quebec (Province)",
      "Montr\u00e9al",
      "Archdioc\u00e8se de Qu\u00e9bec"
  ],
  "first_publish_date": "1986",
  "subject_people": [
      "Archev\u00eaque (1867-1870 : Baillargeon)"
  ],
  "key": "/works/OL12548230W",
  "authors": [
    {
      "type": {
          "key": "/type/author_role"
      },
      "author": {
          "key": "/authors/OL5561187A"
      }
  },
  {
    "type": {
        "key": "/type/author_role"
    },
    "author": {
        "key": "/authors/OL46053A"
    }
  }
  ],
  "latest_revision": 7,
  "subject_times": [
      "28 mai 1870"
  ],
  "type": {
      "key": "/type/work"
  },
  "subjects": [
      "Fires",
      "Church and social problems",
      "Finance",
      "Catholic Church",
      "Incendies",
      "Finances",
      "\u00c9glise catholique",
      "\u00c9glise et probl\u00e8mes sociaux"
  ],
  "revision": 7
}

  export const authorMock = {
    "personal_name": "J. K. Rowling",
    "key": "/authors/OL23919A",
    "entity_type": "person",
    "birth_date": "31 July 1965",
    "links": [
      {
        "title": "Official Site",
        "url": "http://www.jkrowling.com/",
        "type": {
          "key": "/type/link"
        }
      }
    ],
    "alternate_names": [
      "Joanne Rowling",
      "Joanne K. Rowling",
      "Jo Murray",
      "Kennilworthy Whisp",
      "JK Rowling",
      "Robert Galbraith",
      "Джоан Роулінг",
      "Dzhoan Rouling",
      "J.K. Rowling",
      "ROWLING",
      "روبرت غالبريث - Robert Galbraith",
      "Rouling Dzh.K.",
      "Newt Scamander",
      "Newton Scamander",
      "J. K Rowling (creator) Jack Thorne",
      "J.k. Rowling",
      "Rowling.J.K.",
      "J K Rowling",
      "J. K Rowling",
      "J-K Rowling",
      "Joanne K Rowling",
      "J. K. ROWLING"
    ],
    "name": "J. K. Rowling",
    "remote_ids": {
      "viaf": "116796842",
      "goodreads": "1077326",
      "storygraph": "6ca9e5f3-d270-4ecf-a0eb-226d334c095e",
      "isni": "000000012148628X",
      "librarything": "rowlingjk",
      "amazon": "B000AP9A6K",
      "wikidata": "Q34660"
    },
    "type": {
      "key": "/type/author"
    },
    "title": "OBE",
    "bio": "Joanne \"Jo\" Murray, OBE (née Rowling), better known under the pen name J. K. Rowling, is a British author best known as the creator of the Harry Potter fantasy series, the idea for which was conceived whilst on a train trip from Manchester to London in 1990. The Potter books have gained worldwide attention, won multiple awards, sold more than 400 million copies, and been the basis for a popular series of films.",
    "fuller_name": "Joanne \"Jo\" Rowling",
    "wikipedia": "http://en.wikipedia.org/wiki/J._K._Rowling",
    "source_records": [
      "amazon:8893817055",
      "amazon:4863895666",
      "amazon:1526618249",
      "amazon:8862561512",
      "amazon:1526618230",
      "amazon:6073193009",
      "amazon:0747574286",
      "amazon:8327158775",
      "amazon:841810791X",
      "amazon:2246810663",
      "amazon:3548285287",
      "amazon:7020150705",
      "bwb:9788498382686",
      "amazon:9123513683",
      "amazon:1526618354",
      "amazon:6041160008",
      "amazon:1526622807",
      "amazon:5353044592",
      "amazon:060641519X",
      "amazon:8327150731",
      "bwb:9780751579956",
      "amazon:9750843878",
      "amazon:9124083836",
      "amazon:286866086X",
      "amazon:2075094551",
      "amazon:3551559201",
      "amazon:9124087181",
      "amazon:1804220272",
      "bwb:9781526624536",
      "amazon:0606323473",
      "amazon:8983927623",
      "amazon:8418174404",
      "amazon:0747598460",
      "amazon:8498389119",
      "amazon:8498388260",
      "amazon:8532531776",
      "amazon:886715818X",
      "amazon:849838267X",
      "bwb:9788418797125",
      "amazon:9124087173",
      "amazon:0606415181",
      "ia:harrypotteresfon0000rowl",
      "amazon:4915512495",
      "amazon:0807281751",
      "bwb:9786073816779",
      "bwb:9781484474112",
      "amazon:1551926431",
      "ia:haeripotopulsajo0000rowl_g0v1",
      "amazon:6555320222",
      "amazon:9124083895",
      "amazon:912408719X",
      "amazon:9124078867",
      "ia:harrypotterylapi0000rowl_q5r6",
      "amazon:8498384451",
      "amazon:2840116464",
      "bwb:9780316263825",
      "amazon:0545850568",
      "bwb:9798769805622",
      "amazon:1551927004",
      "promise:bwb_daily_pallets_2021-06-17",
      "amazon:1547904135",
      "amazon:0439342562",
      "bwb:9788418797620",
      "promise:bwb_daily_pallets_2023-04-27:W8-BSR-220",
      "amazon:4915512576",
      "promise:bwb_daily_pallets_2022-10-26:O8-CYF-463",
      "promise:bwb_daily_pallets_2023-04-27:W8-BSR-217",
      "promise:bwb_daily_pallets_2023-06-15:O9-AKW-753",
      "bwb:9781526646712",
      "promise:bwb_daily_pallets_2022-11-08:P8-BBS-730",
      "promise:bwb_daily_pallets_2022-06-01",
      "amazon:9124130907",
      "promise:bwb_daily_pallets_2022-11-30:O8-BXE-291",
      "amazon:8418797770",
      "promise:bwb_daily_pallets_2023-06-30:W8-CCQ-102",
      "amazon:8532530176",
      "promise:bwb_daily_pallets_2022-10-17",
      "bwb:9780747569411",
      "amazon:9123951435",
      "amazon:9123962836",
      "amazon:3551359261",
      "amazon:8893814536",
      "amazon:8380082389",
      "promise:bwb_daily_pallets_2022-11-23",
      "amazon:8372786941",
      "promise:bwb_daily_pallets_2023-11-15:P8-CRI-240",
      "amazon:8372780161",
      "marc:harvard_bibliographic_metadata/ab.bib.11.20150123.full.mrc:787625145:1003",
      "bwb:9788419275202",
      "bwb:9780798184380"
    ],
    "photos": [5543033, -1],
    "latest_revision": 119,
    "revision": 119,
    "created": {
      "type": "/type/datetime",
      "value": "2008-04-01T03:28:50.625462"
    },
    "last_modified": {
      "type": "/type/datetime",
      "value": "2024-09-11T16:09:06.481353"
    }
  }